---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
    # wait for docker service to be up before running docker build
    - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
    - docker build -t pttg-rps-enquiry:$${DRONE_COMMIT_SHA} . --no-cache
  when:
    event:
    - push

    # Regression test manually

- name: scan-image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  pull: always
  environment:
    IMAGE_NAME: pttg-rps-enquiry:${DRONE_COMMIT_SHA}
    FAIL_ON_DETECTION: false
  when:
    event:
    - push

- name: install-docker-image-with-githash-tag
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
    - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} quay.io
    - docker tag pttg-rps-enquiry:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/pttg-rps-enquiry:$${DRONE_COMMIT_SHA}
    - docker push quay.io/ukhomeofficedigital/pttg-rps-enquiry:$${DRONE_COMMIT_SHA}
  environment:
    DOCKER_USERNAME: ukhomeofficedigital+pttg
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
    - push

- name: install-docker-image-from-feature-branch-build
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
    - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} quay.io
    - docker tag pttg-rps-enquiry:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/pttg-rps-enquiry:$${DRONE_BRANCH}
    - docker push quay.io/ukhomeofficedigital/pttg-rps-enquiry:$${DRONE_BRANCH}
  environment:
    DOCKER_USERNAME: ukhomeofficedigital+pttg
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
      - push
    branch:
      exclude:
        - master
        

- name: install-docker-image-from-master-branch-build
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
    - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} quay.io
    - docker tag pttg-rps-enquiry:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/pttg-rps-enquiry:latest
    - docker push quay.io/ukhomeofficedigital/pttg-rps-enquiry:latest
    - docker tag pttg-rps-enquiry:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/pttg-rps-enquiry:build-$${DRONE_BUILD_NUMBER}
    - docker push quay.io/ukhomeofficedigital/pttg-rps-enquiry:build-$${DRONE_BUILD_NUMBER}
  environment:
    DOCKER_USERNAME: ukhomeofficedigital+pttg
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
      - push
    branch:
      - master

- name: tag-docker-image-with-git-tag
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
    - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} quay.io
    - docker tag pttg-rps-enquiry:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/pttg-rps-enquiry:$${DRONE_TAG}
    - docker push quay.io/ukhomeofficedigital/pttg-rps-enquiry:$${DRONE_TAG}
  environment:
    DOCKER_USERNAME: ukhomeofficedigital+pttg
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event: [tag]

- name: clone-kube-project
  pull: if-not-exists
  image: plugins/git
  commands:
    - git clone https://github.com/UKHomeOffice/kube-pttg-rps-enquiry-form.git
  when:
    event:
      - promote

- name: deployment-to-not-prod
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd:v1.17.0
  commands:
    - cd kube-pttg-rps-enquiry-form
    - ./deploy.sh
  environment:
    ENVIRONMENT: ${DRONE_DEPLOY_TO}
    KUBE_NAMESPACE: pttg-rps-enquiry-${DRONE_DEPLOY_TO}
    KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    WHITELIST: 62.25.109.196/32,52.48.127.150/32,52.48.127.151/32,52.48.127.152/32,52.48.127.153/32,52.209.62.128/25,52.56.62.128/25,185.22.224.96,185.22.224.96/32,185.22.226.96/32,213.251.23.180/30,213.251.23.184/30,213.251.23.188/30,148.253.134.213/32,167.98.162.0/25,167.98.158.128/25,86.4.17.136
    PTTG_RPS_DEV:
      from_secret: pttg_rps_dev
    PTTG_RPS_TEST:
      from_secret: pttg_rps_test
    NOTIFY_RECIPIENT_NOTPROD:
      from_secret: notify_recipient_notprod
    BASIC_AUTH:
      from_secret: basic_auth
  when:
    event:
    - promote
    target:
    - dev
    - test

- name: deploy-to-prod
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd:v1.17.0
  commands:
    - cd kube-pttg-rps-enquiry-form
    - ./deploy.sh
  environment:
    ENVIRONMENT: ${DRONE_DEPLOY_TO}
    KUBE_NAMESPACE: pttg-rps-enquiry-${DRONE_DEPLOY_TO}
    KUBE_SERVER: https://kube-api-prod.prod.acp.homeoffice.gov.uk
    PTTG_RPS_PR:
      from_secret: pttg_rps_pr
    NOTIFY_RECIPIENT_PROD:
      from_secret: notify_recipient_prod
  when:
    event:
    - promote
    target:
    - pr

services:
- name: docker-in-docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

- name: anchore-submission-server
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  pull: always
  commands:
    - /run.sh server