FROM quay.io/ukhomeofficedigital/nodejs-base:v8

WORKDIR /test

COPY package.json package.json
COPY codecept.conf.js codecept.conf.js
COPY config.js config.js
COPY apps apps/
COPY logger.js logger.js
COPY test test/

RUN npm --loglevel warn install # eslint

CMD npm run test
